title: ALGERIA FC
description: > # this means to ignore newlines until "baseurl:"
  Where Algerian Football lives 
permalink: '/:title'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://algeriafc.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: Algeria_FC #if your site has a twitter account, enter it here

# Author Settings
author: ALGERIA FC # add your name
author-img: afclogo2.jpg # add your photo
about-author: Where Algerian Football lives # add description
social-twitter: Algeria_FC
social-facebook: false
social-github: false
social-linkedin: false
social-email: false

# Disqus
discus-identifier: false # add your discus identifier

# Tracker
analytics: G-2D32GVQHBY 

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
